### ISSUE TITLE
Unable to Save in Prod

### ISSUE THREAD

**Issue by Unthrottled** [cyclic-reference/acari-landing#15]
```
 java.lang.NoSuchMethodError: org.springframework.core.io.buffer.DataBufferUtils.readInputStream(Ljava/util/concurrent/Callable;Lorg/springframework/core/io/buffer/DataBufferFactory;I)Lreactor/core/publisher/Flux;
web-service_1  | 	at org.springframework.http.codec.multipart.SynchronossPartHttpMessageReader$DefaultSynchronossPart.content(SynchronossPartHttpMessageReader.java:270) ~[spring-web-5.0.3.BUILD-SNAPSHOT.jar!/:5.0.3.BUILD-SNAPSHOT]
web-service_1  | 	at io.acari.landing.project.ImageHandler.lambda$saveImage$0(ImageHandler.java:31) ~[classes!/:na]
web-service_1  | 	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:347) ~[reactor-core-3.1.2.RELEASE.jar!/:3.1.2.RELEASE]
web-service_1  | 	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73) ~[reactor-core-3.1.2.RELEASE.jar!/:3.1.2.RELEASE]
web-service_1  | 	at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:724) ~[reactor-core-3.1.2.RELEASE.jar!/:3.1.2.RELEASE]
web-service_1  | 	at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:655) ~[reactor-core-3.1.2.RELEASE.jar!/:3.1.2.RELEASE]
web-service_1  | 	at reactor.core.publisher.FluxCreate$SerializedSink.next(FluxCreate.java:146) ~[reactor-core-3.1.2.RELEASE.jar!/:3.1.2.RELEASE]
web-service_1  | 	at org.springframework.http.codec.multipart.SynchronossPartHttpMessageReader$FluxSinkAdapterListener.onPartFinished(SynchronossPartHttpMessageReader.java:188) ~[spring-web-5.0.3.BUILD-SNAPSHOT.jar!/:5.0.3.BUILD-SNAPSHOT]
web-service_1  | 	at org.synchronoss.cloud.nio.multipart.NioMultipartParser.partComplete(NioMultipartParser.java:630) ~[nio-multipart-parser-1.1.0.jar!/:na]
web-service_1  | 	at org.synchronoss.cloud.nio.multipart.NioMultipartParser.write(NioMultipartParser.java:437) ~[nio-multipart-parser-1.1.0.jar!/:na]
web-service_1  | 	at org.synchronoss.cloud.nio.multipart.NioMultipartParser.write(NioMultipartParser.java:370) ~[nio-multipart-parser-1.1.0.jar!/:na]
web-service_1  | 	at org.springframework.http.codec.multipart.SynchronossPartHttpMessageReader$SynchronossPartGenerator.lambda$accept$0(SynchronossPartHttpMessageReader.java:136) ~[spring-web-5.0.3.BUILD-SNAPSHOT.jar!/:5.0.3.BUILD-SNAPSHOT]
web-service_1  | 	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:130) ~[reactor-core-3.1.2.RELEASE.jar!/:3.1.2.RELEASE]
web-service_1  | 	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:108) ~[reactor-core-3.1.2.RELEASE.jar!/:3.1.2.RELEASE]
web-service_1  | 	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:185) ~[reactor-core-3.1.2.RELEASE.jar!/:3.1.2.RELEASE]
web-service_1  | 	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:108) ~[reactor-core-3.1.2.RELEASE.jar!/:3.1.2.RELEASE]
web-service_1  | 	at reactor.ipc.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:211) ~[reactor-netty-0.7.2.RELEASE.jar!/:0.7.2.RELEASE]
web-service_1  | 	at reactor.ipc.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:326) ~[reactor-netty-0.7.2.RELEASE.jar!/:0.7.2.RELEASE]
web-service_1  | 	at reactor.ipc.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:319) ~[reactor-netty-0.7.2.RELEASE.jar!/:0.7.2.RELEASE]
web-service_1  | 	at reactor.ipc.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:366) ~[reactor-netty-0.7.2.RELEASE.jar!/:0.7.2.RELEASE]
web-service_1  | 	at reactor.ipc.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:132) ~[reactor-netty-0.7.2.RELEASE.jar!/:0.7.2.RELEASE]
web-service_1  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.17.Final.jar!/:4.1.17.Final]
web-service_1  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.17.Final.jar!/:4.1.17.Final]
web-service_1  | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.17.Final.jar!/:4.1.17.Final]
web-service_1  | 	at reactor.ipc.netty.http.server.HttpServerHandler.channelRead(HttpServerHandler.java:139) [reactor-netty-0.7.2.RELEASE.jar!/:0.7.2.RELEASE]
web-service_1  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.17.Final.jar!/:4.1.17.Final]
web-service_1  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.17.Final.jar!/:4.1.17.Final]
web-service_1  | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.17.Final.jar!/:4.1.17.Final]
web-service_1  | 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438) [netty-transport-4.1.17.Final.jar!/:4.1.17.Final]
web-service_1  | 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [netty-codec-4.1.17.Final.jar!/:4.1.17.Final]
web-service_1  | 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [netty-codec-4.1.17.Final.jar!/:4.1.17.Final]
web-service_1  | 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253) [netty-transport-4.1.17.Final.jar!/:4.1.17.Final]
web-service_1  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.17.Final.jar!/:4.1.17.Final]
web-service_1  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.17.Final.jar!/:4.1.17.Final]
web-service_1  | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.17.Final.jar!/:4.1.17.Final]
web-service_1  | 	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1379) [netty-handler-4.1.17.Final.jar!/:4.1.17.Final]
web-service_1  | 	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1158) [netty-handler-4.1.17.Final.jar!/:4.1.17.Final]
web-service_1  | 	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1193) [netty-handler-4.1.17.Final.jar!/:4.1.17.Final]
web-service_1  | 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) [netty-codec-4.1.17.Final.jar!/:4.1.17.Final]
web-service_1  | 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) [netty-codec-4.1.17.Final.jar!/:4.1.17.Final]
web-service_1  | 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [netty-codec-4.1.17.Final.jar!/:4.1.17.Final]
web-service_1  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.17.Final.jar!/:4.1.17.Final]
web-service_1  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.17.Final.jar!/:4.1.17.Final]
web-service_1  | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.17.Final.jar!/:4.1.17.Final]
web-service_1  | 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) [netty-transport-4.1.17.Final.jar!/:4.1.17.Final]
web-service_1  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.17.Final.jar!/:4.1.17.Final]
web-service_1  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.17.Final.jar!/:4.1.17.Final]
web-service_1  | 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) [netty-transport-4.1.17.Final.jar!/:4.1.17.Final]
web-service_1  | 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138) [netty-transport-4.1.17.Final.jar!/:4.1.17.Final]
web-service_1  | 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [netty-transport-4.1.17.Final.jar!/:4.1.17.Final]
web-service_1  | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) [netty-transport-4.1.17.Final.jar!/:4.1.17.Final]
web-service_1  | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) [netty-transport-4.1.17.Final.jar!/:4.1.17.Final]
web-service_1  | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [netty-transport-4.1.17.Final.jar!/:4.1.17.Final]
web-service_1  | 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.17.Final.jar!/:4.1.17.Final]
web-service_1  | 	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111-internal]
web-service_1  | 
```

**Comment by Unthrottled** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Unable to save projects in prod.](https://trello.com/c/hCNJoW0U/48-unable-to-save-projects-in-prod)
